### PR TITLE
Fix Eureka's 'List Apps' endpoint to support both with/without trailing slash

### LINKED ISSUE #46: Eureka's "List Apps" endpoint requires a trailing slash
Eureka's "List Apps" endpoint (`GET /api/eureka//v2/apps/`) requires the client to add a trailing slash into the URL, and returns a `{"Error":"Resource not found"}` when the trailing slash is absent. This is inconsistent with other Eureka endpoints which do not require a trailing slash, as well as the native Amalgam8 APIs which also do not require a trailing slash.

So, we need to...
1. Verify that the Eureka API specification doesn't require that trailing slash (i.e., and not invoked by the Eureka client)
2. Fix the code so that the trailing slash requirement is removed.

### PR DESCRIPTION
**Pull request by zcahana**
Fixes #46

### CODE REVIEW

**Comment by zachidan** [comment]
@zcahana: looks ok

**Comment by rshriram** [comment]
Is this going into a new registry image as 0.2.2?

**Comment by zcahana** [comment]
@shriram It could, but then it'll drag with it some additional commits which are already merged into master. Most notably, that's the A8_ prefix on the env vars. I'm thinking this should better go into 0.3, what do you think?

**Comment by shriram** [comment]
I think you meant to at-mention @rshriram and not me (sans the `r`). Cheers, and good luck with the project!

**Comment by zcahana** [comment]
@shriram you're most certainly right. Sorry for the (now double) bother! ;)

**Pull request merged**
